import './globals.css'
import {Sora} from 'next/font/google'

// font setting
const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// components
import Nav from '../components/Nav'
import Header from '../components/Header'
import TopLeftImg from '../components/TopLeftImg'
import Transition from '../components/Transition'
import {AnimatePresence, motion} from 'framer-motion'

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head>
        <title>GK's Portfolio</title>
      </head>
      <body className={`page bg-site text-white bg-cover bg-no-repeat ${sora.variable}
       font-sora relative`}>
        <TopLeftImg />
        <Nav />
        <Header />
        {children}
      </body>
    </html>
  )
}
